import type { Database } from "bun:sqlite";

interface ChangeSetRow {
  id: string;
  task_id: string;
  title: string;
  description: string;
  source_branch: string;
  target_branch: string;
  worktree_path: string;
}

interface CommentRow {
  severity: string;
  body: string;
  file_path: string | null;
  resolved: number;
}

interface CheckRunRow {
  name: string;
  status: string;
  exit_code: number | null;
}

interface DecisionRow {
  topic: string;
  choice: string;
  rationale: string;
}

export class PRBodyBuilder {
  constructor(private db: Database) {}

  build(changeSetId: string): string {
    const cs = this.db
      .query<ChangeSetRow, [string]>("SELECT * FROM change_sets WHERE id = ?")
      .get(changeSetId);
    if (!cs) throw new Error(`ChangeSet ${changeSetId} not found`);

    const comments = this.db
      .query<CommentRow, [string]>(
        "SELECT severity, body, file_path, resolved FROM review_comments WHERE change_set_id = ? ORDER BY severity, created_at"
      )
      .all(changeSetId);

    const checkRuns = this.db
      .query<CheckRunRow, [string]>(
        "SELECT name, status, exit_code FROM check_runs WHERE change_set_id = ? ORDER BY name"
      )
      .all(changeSetId);

    const decisions = this.db
      .query<DecisionRow, [string]>(
        "SELECT topic, choice, rationale FROM decisions WHERE change_set_id = ? ORDER BY ts"
      )
      .all(changeSetId);

    // Diff stat from worktree
    let diffStat = "_No diff available_";
    try {
      const proc = Bun.spawnSync(["git", "diff", "--stat", `${cs.target_branch}...HEAD`], {
        cwd: cs.worktree_path,
        stdout: "pipe",
        stderr: "pipe",
      });
      const out = proc.stdout?.toString().trim();
      if (out) diffStat = `\`\`\`\n${out}\n\`\`\``;
    } catch {}

    const blocking = comments.filter((c) => c.severity === "blocking");
    const resolved = blocking.filter((c) => c.resolved);
    const advisory = comments.filter((c) => c.severity !== "blocking");

    const sections: string[] = [
      `## Summary`,
      cs.description || "_No description provided_",
      "",
      `## Changes`,
      diffStat,
      "",
      `## Review Results`,
    ];

    if (checkRuns.length > 0) {
      sections.push("| Check | Status |", "|-------|--------|");
      for (const cr of checkRuns) {
        sections.push(`| ${cr.name} | ${cr.status} |`);
      }
    } else {
      sections.push("_No check runs recorded_");
    }

    sections.push("");
    sections.push("### Blocking Comments Resolved");
    if (resolved.length > 0) {
      for (const c of resolved) {
        sections.push(`- ${c.body}`);
      }
    } else {
      sections.push("_None_");
    }

    sections.push("");
    sections.push("### Unresolved Advisory Comments");
    if (advisory.length > 0) {
      for (const c of advisory) {
        sections.push(`- [${c.severity}] ${c.body}`);
      }
    } else {
      sections.push("_None_");
    }

    sections.push("");
    sections.push("## Decisions");
    if (decisions.length > 0) {
      for (const d of decisions) {
        sections.push(`**${d.topic}**: ${d.choice} — ${d.rationale}`);
        sections.push("");
      }
    } else {
      sections.push("_No decisions recorded_");
    }

    sections.push("---");
    sections.push(`*Generated by localsdlc — inner loop ChangeSet: ${changeSetId}*`);

    return sections.join("\n");
  }
}
